### ISSUE TITLE
Drv.Open Env.OpenCon Pool.Get.func1 recovered:runtime error invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by liuluheng** [rana/ora#118]
![olm9a olle it ir a3i1c](https://cloud.githubusercontent.com/assets/5222552/18835530/15033388-842e-11e6-939b-d0984050bf47.png)

Oracle:11.2.0.3 OS:RHEL GO:1.7.1
When I Insert Records to a table too many times (> 10000 times) It panic like above, any clue about this??

**Comment by tgulacsi** [comment]
The lines from tha panic:
```env.OpenCon
pool.Get
p.sesCfg.StmtCfg = srv.env.cfg.StmtCfg```

as p is used before (p.Lock), thus p is not nil there; the fresh srv's env or env.cfg is nil.
I don't know how this can happen - can you share a reproduction?

You can also try master (esp. dee3dff)?

**Comment by liuluheng** [comment]
temporarily switched to the go-oci8...

**Comment by omerkirk** [comment]
I have the same issue with Go 1.7.1 using GODEBUG=cgocheck=0. Below is the stacktrace: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4f767b]

goroutine 79957 [running]:
panic(0x7f9f60, 0xc4200120d0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
gopkg.in/rana/ora%2ev3.(*Pool).Get(0xc420016b40, 0x0, 0x0, 0x0)
        /home/kokteyl/go/src/gopkg.in/rana/ora.v3/pool.go:135 +0x21b
gopkg.in/rana/ora%2ev3.(*Env).OpenCon(0xc4200b4500, 0xc4200ac2d0, 0x8d, 0x0, 0x0, 0x0)
        /home/kokteyl/go/src/gopkg.in/rana/ora.v3/env.go:205 +0x19b
gopkg.in/rana/ora%2ev3.(*Drv).Open(0xc4200ae4e0, 0xc4200ac2d0, 0x8d, 0x41415e, 0x55555555555555, 0x13, 0x6662633032316562)
        /home/kokteyl/go/src/gopkg.in/rana/ora.v3/drv.go:165 +0x70
database/sql.(*DB).conn(0xc4200c4580, 0xc420ab6f01, 0xc420ab6c00, 0x2fc, 0x2fc)
        /usr/local/go/src/database/sql/sql.go:824 +0x24e
database/sql.(*DB).prepare(0xc4200c4580, 0xc420ab6f00, 0x2fc, 0xc31101, 0x2fc, 0x2fc, 0x5)
        /usr/local/go/src/database/sql/sql.go:982 +0x4c
database/sql.(*DB).Prepare(0xc4200c4580, 0xc420ab6f00, 0x2fc, 0x0, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:964 +0x60
github.com/omerkirk/sqlx.Preparex(0xc311e0, 0xc4200f7500, 0xc420ab6f00, 0x2fc, 0xc4200f7500, 0x2fc, 0xc4200154a0)
        /home/kokteyl/go/src/github.com/omerkirk/sqlx/sqlx.go:612 +0x4f
github.com/omerkirk/sqlx.prepareNamed(0xc379a0, 0xc4200f7500, 0x87afb9, 0x2fc, 0x670bbc, 0x80003, 0x0)
        /home/kokteyl/go/src/github.com/omerkirk/sqlx/named.go:121 +0x186


```

**Comment by tgulacsi** [comment]
Can you try the master branch?
dee3dff should fix this!

**Comment by omerkirk** [comment]
Will do, I can't reproduce the issue so I can't be sure if it is fixed. 

Is there a release for this, how should I get the master branch.

**Comment by tgulacsi** [comment]
cd $GOPATH/src/gopkg.in/rana/ora.v3
    git checkout -f master
    git pull origin master

But I've tagged a new release (v3.7.2), so a `go get -u gopkg.in/rana/ora.v3` will be enough.

**Comment by omerkirk** [comment]
Started using the master in production now, will report if anything comes up.
