### ISSUE TITLE
Nil Pointer dereference

### ISSUE THREAD

**Issue by omerkirk** [rana/ora#119]
Using the latest release 3.7.2 and Go 1.7.1.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4f572a]

goroutine 1 [running]:
panic(0x7faa40, 0xc4200120d0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
gopkg.in/rana/ora%2ev3.(*Con).sysName(0xc45c3f8080, 0xc491de5a48, 0x1)
        /home/kokteyl/go/src/gopkg.in/rana/ora.v3/conn.go:145 +0x5a
gopkg.in/rana/ora%2ev3.(*Con).log(0xc45c3f8080, 0x1, 0x0, 0x0, 0x0)
        /home/kokteyl/go/src/gopkg.in/rana/ora.v3/conn.go:152 +0x61
gopkg.in/rana/ora%2ev3.(*Con).Prepare(0xc45c3f8080, 0xc452a315c0, 0x5a, 0xc4571a7a90, 0xc4571a7b00, 0xc46df6fb08, 0xc46df6fba8)
        /home/kokteyl/go/src/gopkg.in/rana/ora.v3/conn.go:108 +0x59
database/sql.(*DB).exec(0xc42034e0b0, 0xc452a315c0, 0x5a, 0xc46df6fbb0, 0x1, 0x1, 0xc46047b801, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/database/sql/sql.go:1047 +0x1fd
database/sql.(*DB).Exec(0xc42034e0b0, 0xc452a315c0, 0x5a, 0xc46df6fbb0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:1010 +0xa2

```

**Comment by tgulacsi** [comment]
I'm not sure whether this panic has anything in common with the original problem, but I've fixed it at master (85ea782).

**Comment by omerkirk** [comment]
I can't get the latest master with the method you gave in the other issue. Is there any other way or must there be a release tagged.

**Comment by tgulacsi** [comment]
cd $GOPATH/src/gopkg.in/rana/
    rm -rf ora.v3
    git clone https://github.com/rana/ora ora.v3
    cd ora.v3 && go install

**Comment by omerkirk** [comment]
That worked thanks. Will let you know if I get any more panics.
