### ISSUE TITLE
database/sql API ```SetConnMaxLifetime()``` lead to panic

### ISSUE THREAD

**Issue by xiongHW** [rana/ora#131]
HI,
  I use the database/sql API ```SetConnMaxLifetime()``` to set the max lifetime of the connection in my progrem. But it reports data race and lead to panic.
  The panic is as below!

```
==================
WARNING: DATA RACE
Write at 0x00c420322868 by goroutine 78:
  gopkg.in/rana/ora%2ev3.(*Stmt).close.func1()
      /home/golang/src/gopkg.in/rana/ora.v3/stmt.go:125 +0x26f
  gopkg.in/rana/ora%2ev3.(*Stmt).close()
      /home/golang/src/gopkg.in/rana/ora.v3/stmt.go:154 +0x24d
  gopkg.in/rana/ora%2ev3.(*stmtList).closeAll()
      /home/golang/src/gopkg.in/rana/ora.v3/type.go:1236 +0xf6
  gopkg.in/rana/ora%2ev3.(*Ses).close()
      /home/golang/src/gopkg.in/rana/ora.v3/ses.go:194 +0x28c
  gopkg.in/rana/ora%2ev3.(*sesList).closeAll()
      /home/golang/src/gopkg.in/rana/ora.v3/type.go:1112 +0xf6
  gopkg.in/rana/ora%2ev3.(*Srv).close()
      /home/golang/src/gopkg.in/rana/ora.v3/srv.go:120 +0x246
  gopkg.in/rana/ora%2ev3.(*Srv).Close()
      /home/golang/src/gopkg.in/rana/ora.v3/srv.go:89 +0x12d
  gopkg.in/rana/ora%2ev3.(*idlePool).Put.func1()
      /home/golang/src/gopkg.in/rana/ora.v3/pool.go:461 +0x152

Previous read at 0x00c420322868 by goroutine 32:
  gopkg.in/rana/ora%2ev3.(*Stmt).Close()
      /home/golang/src/gopkg.in/rana/ora.v3/stmt.go:85 +0xb3
  gopkg.in/rana/ora%2ev3.(*DrvStmt).Close()
      /home/golang/src/gopkg.in/rana/ora.v3/drvStmt.go:37 +0xe0
  database/sql.(*Rows).Close()
      /usr/local/go/src/database/sql/sql.go:1873 +0x215
  database/sql.(*Row).Scan()
      /usr/local/go/src/database/sql/sql.go:1927 +0x26e
  main.dbRoutine()
      /home/golang/src/test/main.go:69 +0x17e

Goroutine 78 (running) created at:
  gopkg.in/rana/ora%2ev3.(*idlePool).Put()
      /home/golang/src/gopkg.in/rana/ora.v3/pool.go:463 +0xc8
  gopkg.in/rana/ora%2ev3.sesSrvPB.Close()
      /home/golang/src/gopkg.in/rana/ora.v3/pool.go:195 +0xd2
  gopkg.in/rana/ora%2ev3.(*sesSrvPB).Close()
      <autogenerated>:65 +0x7f
  gopkg.in/rana/ora%2ev3.(*idlePool).Put.func1()
      /home/golang/src/gopkg.in/rana/ora.v3/pool.go:461 +0x152

Goroutine 32 (running) created at:
  main.main()
      /home/golang/src/test/main.go:105 +0x1b1
==================
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x54c85b]

goroutine 59 [running]:
panic(0x68dea0, 0xc42000c1c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1ae
gopkg.in/rana/ora%2ev3.(*Stmt).Close(0xc420322780, 0x0, 0x0)
	/home/golang/src/gopkg.in/rana/ora.v3/stmt.go:89 +0x12b
gopkg.in/rana/ora%2ev3.(*DrvStmt).Close(0xc4200c25b8, 0x0, 0x0)
	/home/golang/src/gopkg.in/rana/ora.v3/drvStmt.go:37 +0xe1
database/sql.(*Rows).Close(0xc42001d2c0, 0xc420495f60, 0x1)
	/usr/local/go/src/database/sql/sql.go:1873 +0x216
database/sql.(*Row).Scan(0xc4202e7bc0, 0xc420495f60, 0x1, 0x1, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:1927 +0x26f
main.dbRoutine()
	/home/golang/src/test/main.go:69 +0x17f
created by main.main
	/home/golang/src/test/main.go:105 +0x1b2

```

**Comment by tgulacsi** [comment]
Can you provide a minimal repro? I see the problem, but want a test case for it!

**Comment by xiongHW** [comment]
My test code

```
func startDB() {
	var err error
	gdb.db, err = sql.Open(driver, dsn)
	if err != nil {
		log.Fatal(err)
	}
	gdb.db.SetMaxIdleConns(32)
	gdb.db.SetConnMaxLifetime(10 * time.Second)
}
```
```
func dbRoutine() {
	tick := time.Tick(1000 * time.Second)
	for {
		select {
		case <-tick:
			log.Println("finish")
			return
		default:
			var temp int
			//gdb.RLock()
			gdb.db.QueryRow("select popid from devicetable where devid=7008").Scan(&temp)
			if rand.Int()%10 == 0 {
				time.Sleep(50 * time.Millisecond)
			}
			//gdb.RUnlock()
		}
	}
}
```
```
func main() {
	log.Println("starting", driver)
	startDB()

	for i := 0; i < 40; i++ {
		go dbRoutine()
	}
	//go checkStat()
	//go switchRoutine()
	select {}
}
```
