### ISSUE TITLE
deadlock when open/close connection

### ISSUE THREAD

**Issue by xiongHW** [rana/ora#133]
Hi
I found there is a deadlock when open/close connection concurrent.
Demo code 
```
func dbRoutine() {
	for {
		var temp int
		gdb.db.QueryRow("select popid from devicetable where devid=7008").Scan(&temp)
		log.Println("running")
		if rand.Int()%10 == 0 {
			time.Sleep(50 * time.Millisecond)
		}
	}
}

func main() {
	log.Println("starting", driver)
	go func() {
		http.ListenAndServe("0.0.0.0:6060", nil)
	}()

	startDB()

	for i := 0; i < 40; i++ {
		go dbRoutine()
	}
	//go checkStat()
	//go switchRoutine()
	select {}
}
```
goroutine stack
```
goroutine 78 [semacquire]:
sync.runtime_Semacquire(0xc4201620dc)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc4201620d8)
	/usr/local/go/src/sync/mutex.go:85 +0xde
gopkg.in/rana/ora%2ev3.(*Pool).Get(0xc4201620c0, 0x0, 0x0, 0x0)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/pool.go:115 +0xae
gopkg.in/rana/ora%2ev3.(*Env).OpenCon(0xc42014a000, 0xa36e48, 0x42, 0x0, 0x0, 0x0)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/env.go:209 +0x28a
gopkg.in/rana/ora%2ev3.(*Drv).Open(0xc420001ba0, 0xa36e48, 0x42, 0x20, 0xc4203ab308, 0x0, 0x1f)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/drv.go:165 +0xa4
database/sql.(*DB).conn(0xc42014e000, 0xc42008a001, 0x0, 0xe6bd20, 0xc4200741a0)
	/usr/local/go/src/database/sql/sql.go:824 +0x257
database/sql.(*DB).query(0xc42014e000, 0xa33c47, 0x2e, 0x0, 0x0, 0x0, 0x1, 0x0, 0xe6bd20, 0xc4200741a0)
	/usr/local/go/src/database/sql/sql.go:1074 +0x5d
database/sql.(*DB).Query(0xc42014e000, 0xa33c47, 0x2e, 0x0, 0x0, 0x0, 0xc42008a000, 0x2, 0xc420475810)
	/usr/local/go/src/database/sql/sql.go:1062 +0xae
database/sql.(*DB).QueryRow(0xc42014e000, 0xa33c47, 0x2e, 0x0, 0x0, 0x0, 0xc420539040)
	/usr/local/go/src/database/sql/sql.go:1143 +0x81
main.dbRoutine()
	/home/xzh/golang/src/test/main.go:68 +0x186
created by main.main
	/home/xzh/golang/src/test/main.go:98 +0x1a5
```
```
goroutine 916 [semacquire]:
sync.runtime_Semacquire(0xc42012cb84)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42012cb80)
	/usr/local/go/src/sync/mutex.go:85 +0xde
gopkg.in/rana/ora%2ev3.(*Srv).Close(0xc42012cb60, 0xc42016b560, 0x0)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/srv.go:80 +0x4f
gopkg.in/rana/ora%2ev3.(*idlePool).Put.func1(0xc4201560d0, 0xe6be60, 0xc42012cb60)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/pool.go:476 +0x14a
created by gopkg.in/rana/ora%2ev3.(*idlePool).Put
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/pool.go:478 +0xc3
```
```
goroutine 885 [semacquire]:
sync.runtime_Semacquire(0xc4201ce71c)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc4201ce718)
	/usr/local/go/src/sync/mutex.go:85 +0xde
gopkg.in/rana/ora%2ev3.(*Ses).close(0xc4201ce6e0, 0x0, 0x0)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/ses.go:159 +0x6f
gopkg.in/rana/ora%2ev3.(*sesList).closeAll(0xc4200de6e0, 0xc420324630)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/type.go:1115 +0xf7
gopkg.in/rana/ora%2ev3.(*Srv).close(0xc42012c0e0, 0x0, 0x0)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/srv.go:120 +0x247
gopkg.in/rana/ora%2ev3.(*Srv).Close(0xc42012c0e0, 0xc4201d4c60, 0x0)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/srv.go:89 +0x12e
gopkg.in/rana/ora%2ev3.(*idlePool).Put.func1(0xc4201560d0, 0xe6be60, 0xc42012c0e0)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/pool.go:476 +0x14a
created by gopkg.in/rana/ora%2ev3.(*idlePool).Put
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/pool.go:478 +0xc3
```

**Comment by tgulacsi** [comment]
Works for me with 42f8d67b9d7c40134a2a4b80439493f9edb875ea.
86ce1d4a969ee1d7bf789759b2590017dee556e1 did have a deadlock, though.

**Comment by xiongHW** [comment]
I see your code in ora/z_issue133.go, dbRoutine runs only three times.
dbRoutine should run infinite until deadlock.

**Comment by xiongHW** [comment]
The follow stack may help you~

GoRroutine 62 hold the ***stmt.mu(stmt.go:83)*** and require ***stmt.ses.mu***
GoRroutine 20 hold srv.mu(srv.go:95) sesList.mu(type.go:1112) ***ses.mu(ses.go:159)*** stmtList.mu(type.go:1236) and require ***stmt.mu***

And then service routine 34 req ***ses.srv.mu(env.go:225)*** which hold by GoRoutine 20, and GoRoutine 34 has held conCharsetMu.
So any of the other service routine, like GoRoutine 6, is waiting for the conCharsetMu.

```
goroutine 62 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0xc42001821c)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc420018218)
	/usr/local/go/src/sync/mutex.go:85 +0xde
gopkg.in/rana/ora%2ev3.(*Stmt).Close(0xc4202fe000, 0x0, 0x0)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/stmt.go:88 +0xb0
gopkg.in/rana/ora%2ev3.(*DrvStmt).Close(0xc420382ed0, 0x0, 0x0)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/drvStmt.go:37 +0xe1
database/sql.(*Rows).Close(0xc420565380, 0xc420457e30, 0x1)
	/usr/local/go/src/database/sql/sql.go:1873 +0x216
database/sql.(*Rows).Next(0xc420565380, 0xa7b418)
	/usr/local/go/src/database/sql/sql.go:1760 +0x14d
database/sql.(*Row).Scan(0xc4203711a0, 0xc420171f80, 0x1, 0x1, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:1916 +0x1be
```
```
goroutine 20 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0xc4202fe0e4)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc4202fe0e0)
	/usr/local/go/src/sync/mutex.go:85 +0xde
gopkg.in/rana/ora%2ev3.(*Stmt).close(0xc4202fe000, 0x0, 0x0)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/stmt.go:100 +0x66
gopkg.in/rana/ora%2ev3.(*stmtList).closeAll(0xc4203dc8a0, 0xc420540d50)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/type.go:1239 +0xf7
gopkg.in/rana/ora%2ev3.(*Ses).close(0xc4200181e0, 0x0, 0x0)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/ses.go:194 +0x28d
gopkg.in/rana/ora%2ev3.(*sesList).closeAll(0xc420375620, 0xc4200142d0)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/type.go:1115 +0xf7
gopkg.in/rana/ora%2ev3.(*Srv).close(0xc4203f43f0, 0x0, 0x0)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/srv.go:120 +0x247
gopkg.in/rana/ora%2ev3.(*Srv).Close(0xc4203f43f0, 0xc420039e60, 0xc420039e47)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/srv.go:89 +0x12e
gopkg.in/rana/ora%2ev3.(*idlePool).Evict(0xc420075110, 0xdf8475800)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/pool.go:439 +0x107
gopkg.in/rana/ora%2ev3.(*Env).NewPool.func1(0xdf8475800)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/pool.go:44 +0x99
gopkg.in/rana/ora%2ev3.(*poolEvictor).SetEvictDuration.func1(0xc4200de620, 0xc4200702a0)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/pool.go:320 +0x18a
created by gopkg.in/rana/ora%2ev3.(*poolEvictor).SetEvictDuration
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/pool.go:326 +0x1a2
```
```
goroutine 34 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0xc4203f4414)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc4203f4410)
	/usr/local/go/src/sync/mutex.go:85 +0xde
gopkg.in/rana/ora%2ev3.(*Env).OpenCon(0xc420168000, 0xa36d88, 0x42, 0xc420012ac0, 0x0, 0x0)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/env.go:225 +0x5d4
gopkg.in/rana/ora%2ev3.(*Drv).Open(0xc420162000, 0xa36d88, 0x42, 0x449150, 0xc420020a0c, 0xc400000002, 0xc420163860)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/drv.go:165 +0xa4
database/sql.(*DB).conn(0xc42016a000, 0x2008a001, 0xc, 0x0, 0x6)
	/usr/local/go/src/database/sql/sql.go:824 +0x257
database/sql.(*DB).query(0xc42016a000, 0xa33b87, 0x2e, 0x0, 0x0, 0x0, 0xc4205afe01, 0x424578, 0xc4204b4400, 0x10)
	/usr/local/go/src/database/sql/sql.go:1074 +0x5d
database/sql.(*DB).Query(0xc42016a000, 0xa33b87, 0x2e, 0x0, 0x0, 0x0, 0xc4205afef8, 0x460791, 0xc4205afef8)
	/usr/local/go/src/database/sql/sql.go:1062 +0xae
database/sql.(*DB).QueryRow(0xc42016a000, 0xa33b87, 0x2e, 0x0, 0x0, 0x0, 0xc420442d00)
	/usr/local/go/src/database/sql/sql.go:1143 +0x81
```
```
goroutine 6 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0x182666c)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0x1826668)
	/usr/local/go/src/sync/mutex.go:85 +0xde
gopkg.in/rana/ora%2ev3.(*Env).OpenCon(0xc420168000, 0xa36d88, 0x42, 0xc420072b40, 0x0, 0x0)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/env.go:221 +0x4a7
gopkg.in/rana/ora%2ev3.(*Drv).Open(0xc420162000, 0xa36d88, 0x42, 0x449150, 0xc42002200c, 0xc400000002, 0xc420162680)
	/home/xzh/golang/src/gopkg.in/rana/ora.v3/drv.go:165 +0xa4
database/sql.(*DB).conn(0xc42016a000, 0x2008a001, 0xc, 0x0, 0x6)
	/usr/local/go/src/database/sql/sql.go:824 +0x257
database/sql.(*DB).query(0xc42016a000, 0xa33b87, 0x2e, 0x0, 0x0, 0x0, 0x596851633f001, 0x42476f, 0xc42005a000, 0x8)
	/usr/local/go/src/database/sql/sql.go:1074 +0x5d
database/sql.(*DB).Query(0xc42016a000, 0xa33b87, 0x2e, 0x0, 0x0, 0x0, 0xc420335ef8, 0x460791, 0xc420335ef8)
	/usr/local/go/src/database/sql/sql.go:1062 +0xae
database/sql.(*DB).QueryRow(0xc42016a000, 0xa33b87, 0x2e, 0x0, 0x0, 0x0, 0xc420499760)
	/usr/local/go/src/database/sql/sql.go:1143 +0x81
```

**Comment by tgulacsi** [comment]
Ok, I want to fix it once and for all.

I've started with parallelizing tests, 
then I changed all config structs to non-pointers,
then I've rewrote all tests to use subtests with for cycles, to shrink the attack vector of changing those config nils to NewStmtCfg() calls,
then I've changed all config struct embeds to atomic.Value with proper Cfg() and SetCfg() methods, to break every code where we may accidentally use cfg directly and maybe modify it,

Now I'm here. The rewrote tests surely has some errors, and the whole code is either race-free, or blocking - depends whether I enable locking in ses.close or not.

The code is at the "cfg-nopointer" branch.
I'm gladly accept suggestions, but maybe we have to rethink the sesList.closeAll in type.go.

**Comment by tgulacsi** [comment]
Hi,

I have some success: "cfg-nopointer" now passes most tests, and esp. the `go run z_race.go` one.
And now the configs can be set per-env/srv/ses/stmt, or *only* the driver env (ora.SetCfg).

**Comment by tgulacsi** [comment]
Ok, the "cfg-nopointer" branch has advanced into an alpha state, please test it!
Most of the tests runs parallel, and no data race should happen (except some with example.go) with -race enabled!

There are some big changes inside, and some middle-sized changes outside. Most notable, the config structs are now immutable, or Set... methods returns a new instance (so they're chainable), but you have to call ora/drv/env/srv/ses/stmt.SetCfg to let them effect.
So `ora.Cfg()....SetChar1(ora.B)` is not enough, you have to call `ora.SetCfg(ora.Cfg().SetChar1(ora.B)`.

@rana, should this be v4.0.0, or just v3.8.0 ?

**Comment by tgulacsi** [comment]
I vote for v4.0.0, and put in all the other breaking changes we want, and make it stable again from v4.1.0!

This way nobody's code will break, and anyone can test the two versions side-to-side (import "gopkg.in/rana/ora.v3" vs. import "gopkg.in/rana/ora.v4").

**Comment by rana** [comment]
Thank you Tamas, sounds good

**Comment by tgulacsi** [comment]
Ok, this is the first case when all the tests passed, most running in parallel, with -race!
Some tests are a little bit flaky, which is unfavorable, but the races were reproducible, and now no race is reported!

@xiongHW , PTAL to the v4 branch!

@rana, now I'm open to suggestions, what (breaking) change should we include?

**Comment by xiongHW** [comment]
Data race still appeared. And there is segment fault
```
==================
WARNING: DATA RACE
Write at 0x00c42032a7b8 by goroutine 91:
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Ses).close.func1()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/ses.go:290 +0xd9
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Ses).close()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/ses.go:330 +0x55b
  stub/vendor/gopkg.in/rana/ora%2ev4.(*sesList).closeAll()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/list.go:204 +0xc1
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Srv).close()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/srv.go:154 +0x293
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Srv).closeWithRemove()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/srv.go:116 +0xb5
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Srv).Close()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/srv.go:103 +0x41
  stub/vendor/gopkg.in/rana/ora%2ev4.(*idlePool).Put.func1()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/pool.go:493 +0x149

Previous read at 0x00c42032a7b8 by goroutine 41:
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Ses).Prep()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/ses.go:446 +0x600
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Con).Prepare()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/conn.go:125 +0x1a1
  database/sql.(*DB).queryConn()
      /usr/local/go/src/database/sql/sql.go:1111 +0x140
  database/sql.(*DB).query()
      /usr/local/go/src/database/sql/sql.go:1079 +0x188
  database/sql.(*DB).Query()
      /usr/local/go/src/database/sql/sql.go:1062 +0xad
  database/sql.(*DB).QueryRow()
      /usr/local/go/src/database/sql/sql.go:1143 +0x80
  main.dbRoutine()
      /home/xzh/golang/src/stub/test/main.go:67 +0xce

Goroutine 91 (running) created at:
  stub/vendor/gopkg.in/rana/ora%2ev4.(*idlePool).Put()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/pool.go:495 +0xc2
  stub/vendor/gopkg.in/rana/ora%2ev4.sesSrvPB.Close()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/pool.go:207 +0xb6
  stub/vendor/gopkg.in/rana/ora%2ev4.(*sesSrvPB).Close()
      <autogenerated>:488 +0x7f
  stub/vendor/gopkg.in/rana/ora%2ev4.(*idlePool).Put.func1()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/pool.go:493 +0x149

Goroutine 41 (running) created at:
  main.main()
      /home/xzh/golang/src/stub/test/main.go:96 +0x1a4
==================
==================
WARNING: DATA RACE
Write at 0x00c4202145b8 by goroutine 146:
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Srv).close.func1()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/srv.go:141 +0xf6
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Srv).close()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/srv.go:168 +0x44f
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Srv).closeWithRemove()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/srv.go:116 +0xb5
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Srv).Close()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/srv.go:103 +0x41
  stub/vendor/gopkg.in/rana/ora%2ev4.(*idlePool).Put.func1()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/pool.go:493 +0x149

Previous read at 0x00c4202145b8 by goroutine 110:
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Srv).checkClosed()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/srv.go:355 +0x96
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Srv).close()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/srv.go:123 +0xf2
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Srv).closeWithRemove()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/srv.go:116 +0xb5
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Srv).Close()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/srv.go:103 +0x41
  stub/vendor/gopkg.in/rana/ora%2ev4.(*idlePool).Put.func1()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/pool.go:493 +0x149

Goroutine 146 (running) created at:
  stub/vendor/gopkg.in/rana/ora%2ev4.(*idlePool).Put()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/pool.go:495 +0xc2
  stub/vendor/gopkg.in/rana/ora%2ev4.sesSrvPB.Close()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/pool.go:207 +0xb6
  stub/vendor/gopkg.in/rana/ora%2ev4.(*sesSrvPB).Close()
      <autogenerated>:488 +0x7f
  stub/vendor/gopkg.in/rana/ora%2ev4.(*idlePool).Put.func1()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/pool.go:493 +0x149

Goroutine 110 (running) created at:
  stub/vendor/gopkg.in/rana/ora%2ev4.(*idlePool).Put()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/pool.go:495 +0xc2
  stub/vendor/gopkg.in/rana/ora%2ev4.sesSrvPB.Close()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/pool.go:207 +0xb6
  stub/vendor/gopkg.in/rana/ora%2ev4.(*sesSrvPB).Close()
      <autogenerated>:488 +0x7f
  stub/vendor/gopkg.in/rana/ora%2ev4.(*idlePool).Put.func1()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/pool.go:493 +0x149
==================
==================
WARNING: DATA RACE
Read at 0x00c420214338 by goroutine 38:
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Pool).Get()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/pool.go:157 +0x3c7
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Env).OpenCon()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/env.go:230 +0x27c
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Drv).Open()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/drv.go:258 +0xb3
  database/sql.(*DB).conn()
      /usr/local/go/src/database/sql/sql.go:824 +0x256
  database/sql.(*DB).query()
      /usr/local/go/src/database/sql/sql.go:1074 +0x5c
  database/sql.(*DB).Query()
      /usr/local/go/src/database/sql/sql.go:1062 +0xad
  database/sql.(*DB).QueryRow()
      /usr/local/go/src/database/sql/sql.go:1143 +0x80
  main.dbRoutine()
      /home/xzh/golang/src/stub/test/main.go:67 +0xce

Previous write at 0x00c420214338 by goroutine 104:
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Srv).close.func1()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/srv.go:141 +0xf6
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Srv).close()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/srv.go:168 +0x44f
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Srv).closeWithRemove()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/srv.go:116 +0xb5
  stub/vendor/gopkg.in/rana/ora%2ev4.(*Srv).Close()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/srv.go:103 +0x41
  stub/vendor/gopkg.in/rana/ora%2ev4.(*idlePool).Put.func1()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/pool.go:493 +0x149

Goroutine 38 (running) created at:
  main.main()
      /home/xzh/golang/src/stub/test/main.go:96 +0x1a4

Goroutine 104 (finished) created at:
  stub/vendor/gopkg.in/rana/ora%2ev4.(*idlePool).Put()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/pool.go:495 +0xc2
  stub/vendor/gopkg.in/rana/ora%2ev4.sesSrvPB.Close()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/pool.go:207 +0xb6
  stub/vendor/gopkg.in/rana/ora%2ev4.(*sesSrvPB).Close()
      <autogenerated>:488 +0x7f
  stub/vendor/gopkg.in/rana/ora%2ev4.(*idlePool).Put.func1()
      /home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/pool.go:493 +0x149
==================
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x2b63a85a8193]

runtime stack:
runtime.throw(0xa5b3d3, 0x2a)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 88 [syscall, locked to thread]:
runtime.cgocall(0x973880, 0xc4206c8ab0, 0x0)
	/usr/local/go/src/runtime/cgocall.go:131 +0xb9 fp=0xc4206c8a68 sp=0xc4206c8a30
stub/vendor/gopkg.in/rana/ora%2ev4._Cfunc_OCIAttrGet(0x23abe60, 0x35, 0xc4200f9010, 0xc420621c2c, 0x1, 0x1963de0, 0x0)
	??:0 +0x6b fp=0xc4206c8ab0 sp=0xc4206c8a68
stub/vendor/gopkg.in/rana/ora%2ev4.(*Rset).paramAttr(0xc4206a8d20, 0x23abe60, 0xc4200f9010, 0xc420621c2c, 0xc400000001, 0x0, 0x1963de0)
	/home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/rset.go:967 +0x19a fp=0xc4206c8b28 sp=0xc4206c8ab0
stub/vendor/gopkg.in/rana/ora%2ev4.(*Rset).open(0xc4206a8d20, 0xc420758f70, 0x1d338b8, 0x0, 0x0)
	/home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/rset.go:496 +0xa0d fp=0xc4206c9580 sp=0xc4206c8b28
stub/vendor/gopkg.in/rana/ora%2ev4.(*Stmt).qryC(0xc420758f70, 0xebcec0, 0xc420076398, 0x1871888, 0x0, 0x0, 0xc4206a8d20, 0x0, 0x0)
	/home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/stmt.go:388 +0x7d4 fp=0xc4206c9a38 sp=0xc4206c9580
stub/vendor/gopkg.in/rana/ora%2ev4.(*Stmt).qry(0xc420758f70, 0x1871888, 0x0, 0x0, 0x0, 0x0, 0xc42043f501)
	/home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/stmt.go:329 +0x89 fp=0xc4206c9aa8 sp=0xc4206c9a38
stub/vendor/gopkg.in/rana/ora%2ev4.(*DrvStmt).Query(0xc42020b8c8, 0x1871888, 0x0, 0x0, 0x1871888, 0x0, 0x0, 0x0)
	/home/xzh/golang/src/stub/vendor/gopkg.in/rana/ora.v4/drvStmt.go:89 +0x1cd fp=0xc4206c9b38 sp=0xc4206c9aa8
database/sql.rowsiFromStatement(0xeb9ac0, 0xc42043f570, 0xebd180, 0xc42020b8c8, 0x0, 0x0, 0x0, 0x10, 0xc4206c9cf8, 0x4246d8, ...)
	/usr/local/go/src/database/sql/sql.go:1655 +0x1ca fp=0xc4206c9c10 sp=0xc4206c9b38
database/sql.(*DB).queryConn(0xc420172000, 0xc42043f570, 0xc4204d4f80, 0xa5c514, 0x2e, 0x0, 0x0, 0x0, 0x95eb20, 0x44ffc3, ...)
	/usr/local/go/src/database/sql/sql.go:1119 +0x250 fp=0xc4206c9d38 sp=0xc4206c9c10
database/sql.(*DB).query(0xc420172000, 0xa5c514, 0x2e, 0x0, 0x0, 0x0, 0xc42008e001, 0x4248cf, 0xc4204be400, 0x8)
	/usr/local/go/src/database/sql/sql.go:1079 +0x189 fp=0xc4206c9de0 sp=0xc4206c9d38
database/sql.(*DB).Query(0xc420172000, 0xa5c514, 0x2e, 0x0, 0x0, 0x0, 0xc42008e080, 0x277fc88f8dcdf66d, 0xc4206c9ee8)
	/usr/local/go/src/database/sql/sql.go:1062 +0xae fp=0xc4206c9e78 sp=0xc4206c9de0
database/sql.(*DB).QueryRow(0xc420172000, 0xa5c514, 0x2e, 0x0, 0x0, 0x0, 0xc4205e74a0)
	/usr/local/go/src/database/sql/sql.go:1143 +0x81 fp=0xc4206c9ef8 sp=0xc4206c9e78
main.dbRoutine()
	/home/xzh/golang/src/stub/test/main.go:67 +0xcf fp=0xc4206c9f90 sp=0xc4206c9ef8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4206c9f98 sp=0xc4206c9f90
created by main.main
	/home/xzh/golang/src/stub/test/main.go:96 +0x1a5
```

**Comment by tgulacsi** [comment]
Tweaked a little. Can you try e8a1b60 ? And what tests do you run? `go run z_race.go` finishes without errors for me.

**Comment by xiongHW** [comment]
I update to 16ce6ea1dd30177a070b025209f5250dad8450ee, and it seems that it is ok. I will run more test cases.
