### ISSUE TITLE
Frequent Timeouts and then Segfault from underlining C Lib

### ISSUE THREAD

**Issue by freedombird9** [rana/ora#192]
I'm using the driver in docker to query some Oracles tables.  

The program somehow always gets SIGSEGV from a C library after running for a while and exits on segfault. It also gets a lot of query timeouts (context deadline exceeded) before it hits segfault error.

The stack trace from the first Goroutine is:

```
Errors in file :
OCI-21500: internal error code, arguments: [KGHFRE3], [0x7FF7D400D388], [], [], [], [], [], []
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7ff85a4f5e72 pc=0x7ff85a4f5e6b]
runtime stack:
runtime.throw(0xa4a0a4, 0x2a)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:274 +0x2db
goroutine 187535 [syscall, locked to thread]:
runtime.cgocall(0x920ba0, 0xc421709370, 0xa495f1)
	/usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc421709330 sp=0xc4217092f0
gopkg.in/rana/ora%2ev4._Cfunc_OCIDescriptorFree(0x7ff7d400d3b0, 0x7ff700000035, 0x0)
	gopkg.in/rana/ora.v4/_obj/_cgo_gotypes.go:626 +0x4d fp=0xc421709370 sp=0xc421709330
gopkg.in/rana/ora%2ev4.(*Rset).open.func2.1(0x7ff7d400d3b0, 0xc400000035, 0xffffffff)
	/go/src/gopkg.in/rana/ora.v4/rset.go:477 +0x68 fp=0xc4217093a8 sp=0xc421709370
gopkg.in/rana/ora%2ev4.(*Rset).open.func2(0xc420d26c90, 0x3, 0x3)
	/go/src/gopkg.in/rana/ora.v4/rset.go:478 +0x5b fp=0xc4217093e0 sp=0xc4217093a8
gopkg.in/rana/ora%2ev4.(*Rset).open(0xc4216f80f0, 0xc4215da6c0, 0x7ff7f405cf18, 0x0, 0x0)
	/go/src/gopkg.in/rana/ora.v4/rset.go:884 +0x3620 fp=0xc421709b98 sp=0xc4217093e0
gopkg.in/rana/ora%2ev4.(*Stmt).qryC(0xc4215da6c0, 0xf1e940, 0xc420c6e600, 0xc4209a2670, 0x1, 0x1, 0xc4216f80f0, 0x0, 0x0)
	/go/src/gopkg.in/rana/ora.v4/stmt.go:442 +0x3e0 fp=0xc421709f18 sp=0xc421709b98
gopkg.in/rana/ora%2ev4.(*DrvStmt).QueryContext.func1(0xc421286900, 0xc4209800d8, 0xc4209800d0, 0xf1e940, 0xc420c6e600, 0xc4209a2670, 0x1, 0x1)
	/go/src/gopkg.in/rana/ora.v4/drvStmt_go1_8.go:76 +0xa6 fp=0xc421709fa0 sp=0xc421709f18
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc421709fa8 sp=0xc421709fa0
created by gopkg.in/rana/ora%2ev4.(*DrvStmt).QueryContext
	/go/src/gopkg.in/rana/ora.v4/drvStmt_go1_8.go:82 +0x30c
```

I think the segfault is triggered in the descriptor free call. I wonder if it's the driver's issue?

I'm using it in a very simple way:

```
ctx, cancel := context.WithTimeout(context.Background(), 10*time.Seconds)
defer cancel()
rows, err := initialedDb.QueryContext(ctx, "sql_query")
// error check and defer rows.Close()
```
I checked my program many times and I don't I have any memory leaks, double frees or anything related.

Golang version: 1.8.1

**Comment by tgulacsi** [comment]
Those lines does not correlate with the current master. Not even with the latest v4.1.7.
Can you try the current master?

**Comment by freedombird9** [comment]
Will `go get -u https://github.com/rana/ora/` give the latest?

**Comment by tgulacsi** [comment]
AFAIK yes.

Yongfeng Zhang <notifications@github.com> ezt írta (időpont: 2017. máj. 2.,
K 6:51):

**Comment by freedombird9** [comment]
So with the `go get -u` command the latest I can get is 4.1.7, according to the CHANGELOG.  I suppose this the latest stable one?  Still got the following error after running for like 10 minutes without any issue:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe78 pc=0x7f75a5531198]
runtime stack:
runtime.throw(0xa487a4, 0x2a)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:274 +0x2db
goroutine 90644 [syscall, locked to thread]:
runtime.cgocall(0x91fea0, 0xc421431b48, 0x100)
	/usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc421431b00 sp=0xc421431ac0
gopkg.in/rana/ora%2ev4._Cfunc_OCIStmtExecute(0x7f7570085540, 0x7f7588060ed8, 0x144e940, 0x0, 0x0, 0x0, 0x0, 0xc400000000)
	gopkg.in/rana/ora.v4/_obj/_cgo_gotypes.go:1355 +0x50 fp=0xc421431b48 sp=0xc421431b00
gopkg.in/rana/ora%2ev4.(*Stmt).qryC.func2(0x7f7570085540, 0x7f7588060ed8, 0x144e940, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/gopkg.in/rana/ora.v4/stmt.go:414 +0x111 fp=0xc421431b98 sp=0xc421431b48
gopkg.in/rana/ora%2ev4.(*Stmt).qryC(0xc42163b7a0, 0xf1d8e0, 0xc420b84c00, 0xc420c3a300, 0x1, 0x1, 0x0, 0x0, 0x0)
	/go/src/gopkg.in/rana/ora.v4/stmt.go:423 +0x2ea fp=0xc421431f18 sp=0xc421431b98
gopkg.in/rana/ora%2ev4.(*DrvStmt).QueryContext.func1(0xc4217fc1e0, 0xc42104c590, 0xc420aa2040, 0xf1d8e0, 0xc420b84c00, 0xc420c3a300, 0x1, 0x1)
	/go/src/gopkg.in/rana/ora.v4/drvStmt_go1_8.go:76 +0xa6 fp=0xc421431fa0 sp=0xc421431f18
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc421431fa8 sp=0xc421431fa0
created by gopkg.in/rana/ora%2ev4.(*DrvStmt).QueryContext
	/go/src/gopkg.in/rana/ora.v4/drvStmt_go1_8.go:82 +0x30c
```

I'm not sure if the latest change in 4.1.8 can fix this.

**Comment by tgulacsi** [comment]
You can try the "master" branch with

  cd $GOPATH/src/gopkg.in/rana/ora.v4
  git checkout -f master
  git pull origin master

but I'm not sure that will help.
stmt.go line 414 is an C.OCIStmtExecute call. Seems that during the call
into the C lib, some signal arrived.

Maybe this is the same as #185 ?
Try disabling the signal handling in tnsnames.ora pointed by TNS_ADMIN
environment variable!

Yongfeng Zhang <notifications@github.com> ezt írta (időpont: 2017. máj. 2.,
K, 19:47):

**Comment by freedombird9** [comment]
That's the weird thing. I'm actually on master branch, and I also did pull, but it says my branch is up-to-date with master.  The CHANGELOG.md, however, still only shows 4.1.7.

**Comment by freedombird9** [comment]
It worked well before Go 1.8, when there was no timeout settings.  I was running 1.7.X at that time.

**Comment by tgulacsi** [comment]
:gthomas@redpath: ~/src/gopkg.in/rana/ora.v4 $ git log
commit de68557a6d0c923a95816dc3bbbe25eb62b35172
Author: Tamas Gulacsi <tgulacsi78@gmail.com>
Date:   Tue May 2 17:43:09 2017 +0200

    do not pool/reuse Rsets

commit b739bf2895556016a90a796ba6afa26232fbeba2
Author: Tamas Gulacsi <tgulacsi78@gmail.com>
Date:   Tue May 2 15:49:05 2017 +0200

    revert e980af32875a9ef8617e24c18e621c7dc834a0a2 for now

commit 7b45a3e8e80b825cb4543abbdaf545173be0c7dd
Author: Tamás Gulácsi <tgulacsi78@gmail.com>
Date:   Tue May 2 07:03:23 2017 +0200

    add test for #191

commit c80677b72ba69847d0d68766fdc7b67ebc55e333
Author: Tamas Gulacsi <tgulacsi78@gmail.com>
Date:   Sat Apr 29 15:30:02 2017 +0200

    bump version number

commit e980af32875a9ef8617e24c18e621c7dc834a0a2
Author: Tamas Gulacsi <tgulacsi78@gmail.com>
Date:   Sat Apr 29 15:26:31 2017 +0200

    Fix missing Rset.Close in DrvQueryResult.Next

commit c54afcf330c0ee86f4a364e57af0b76f9d150bba
Author: Tamas Gulacsi <tgulacsi78@gmail.com>
Date:   Sat Apr 29 14:57:09 2017 +0200

    close rset at the end

    Fixes slow memory leak

commit a008457ebf62b6ae8236c64a603f367684c16277


Yongfeng Zhang <notifications@github.com> ezt írta (időpont: 2017. máj. 2.,
K, 21:50):

**Comment by tgulacsi** [comment]
```
cd $GOPATH/src/gopkg.in
rm -rf ora.v4
git clone https://github.com/rana/ora.git ora.v4
```

gopkg.in/rana/ora.v4 pulls the biggest tag with v4.x.x

**Comment by freedombird9** [comment]
Okay, the gopkg.in is several commits behind.  The github one is up-to-date.

**Comment by freedombird9** [comment]
When do you plan to update `gopkg.in/rana/ora.v4`? Since ora requires import "gopkg.in/rana/ora.v4", it always fetches gopkg.in/rana/ora.v4 according to import scan.  We're doing everything in Docker, so it's kinda hard to involve git there.

**Comment by freedombird9** [comment]
So did some trick to build the latest code into docker image.  After running for about 5 minutes, got:

```
Errors in file :
OCI-21500: internal error code, arguments: [KGHFRE3], [0x7FA7A00C33C0], [], [], [], [], [], []
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7fa828ffae72 pc=0x7fa828ffae6b]
runtime stack:
runtime.throw(0xa4a0c2, 0x2a)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:274 +0x2db
goroutine 47532 [syscall, locked to thread]:
runtime.cgocall(0x9203f0, 0xc42145d340, 0xa4960f)
	/usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc42145d300 sp=0xc42145d2c0
gopkg.in/rana/ora%2ev4._Cfunc_OCIDescriptorFree(0x7fa7a00c33e8, 0x7fa700000035, 0x0)
	gopkg.in/rana/ora.v4/_obj/_cgo_gotypes.go:626 +0x4d fp=0xc42145d340 sp=0xc42145d300
gopkg.in/rana/ora%2ev4.(*Rset).open.func2.1(0x7fa7a00c33e8, 0xc400000035, 0xffffffff)
	/go/src/gopkg.in/rana/ora.v4/rset.go:472 +0x68 fp=0xc42145d378 sp=0xc42145d340
gopkg.in/rana/ora%2ev4.(*Rset).open.func2(0xc4201f6a50, 0x3, 0x3)
	/go/src/gopkg.in/rana/ora.v4/rset.go:473 +0x5b fp=0xc42145d3b0 sp=0xc42145d378
gopkg.in/rana/ora%2ev4.(*Rset).open(0xc420eb41c0, 0xc4204d9c20, 0x7fa7d8034980, 0x0, 0x0)
	/go/src/gopkg.in/rana/ora.v4/rset.go:859 +0x3484 fp=0xc42145db98 sp=0xc42145d3b0
gopkg.in/rana/ora%2ev4.(*Stmt).qryC(0xc4204d9c20, 0xf21de0, 0xc420aa6a80, 0xc4217a4150, 0x1, 0x1, 0xc420eb41c0, 0x0, 0x0)
	/go/src/gopkg.in/rana/ora.v4/stmt.go:446 +0x3c4 fp=0xc42145df18 sp=0xc42145db98
gopkg.in/rana/ora%2ev4.(*DrvStmt).QueryContext.func1(0xc4201dc060, 0xc420964060, 0xc420964048, 0xf21de0, 0xc420aa6a80, 0xc4217a4150, 0x1, 0x1)
	/go/src/gopkg.in/rana/ora.v4/drvStmt_go1_8.go:76 +0xa6 fp=0xc42145dfa0 sp=0xc42145df18
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42145dfa8 sp=0xc42145dfa0
created by gopkg.in/rana/ora%2ev4.(*DrvStmt).QueryContext
	/go/src/gopkg.in/rana/ora.v4/drvStmt_go1_8.go:82 +0x30c
goroutine 1 [semacquire, 7 minutes]:
sync.runtime_Semacquire(0xc420128028)
	/usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc42012801c)
	/usr/local/go/src/sync/waitgroup.go:131 +0x7a
go-jasperlib/kestrel.(*MemcacheReader).Wait(0xc420128000)
	/go/src/go-jasperlib/kestrel/reader.go:685 +0x12a
main.main()
	/go/src/gomq/consumers/AcctRecordNoSqlProcessor/main.go:596 +0x659
```

The stack trace is slightly different each time it got segfault.  Let me try a few more times.

**Comment by freedombird9** [comment]
Or if you know if there's anyway to check timeouts and cancel timed-out queries manually without using the timeout context?  The code worked for me before in Go 1.7.

**Comment by freedombird9** [comment]
Here is another dump from another run:

```
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f4edcd974c2 pc=0x7f4edcd974bb]
runtime stack:
runtime.throw(0xa4a0c2, 0x2a)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:274 +0x2db
goroutine 599 [syscall, locked to thread]:
runtime.cgocall(0x921570, 0xc42130b1b0, 0xa4960f)
	/usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc42130b170 sp=0xc42130b130
gopkg.in/rana/ora%2ev4._Cfunc_OCIStmtRelease(0x7f4e700344c0, 0x18ad940, 0x0, 0x0, 0x0)
	gopkg.in/rana/ora.v4/_obj/_cgo_gotypes.go:1437 +0x4d fp=0xc42130b1b0 sp=0xc42130b170
gopkg.in/rana/ora%2ev4.(*Stmt).close.func1.1(0x7f4e700344c0, 0x18ad940, 0x0, 0x0, 0xfa0)
	/go/src/gopkg.in/rana/ora.v4/stmt.go:158 +0xbd fp=0xc42130b1e8 sp=0xc42130b1b0
gopkg.in/rana/ora%2ev4.(*Stmt).close.func1(0xc42130b630, 0xc4211d8120, 0xc420c28030)
	/go/src/gopkg.in/rana/ora.v4/stmt.go:163 +0xb7 fp=0xc42130b380 sp=0xc42130b1e8
gopkg.in/rana/ora%2ev4.(*Stmt).close(0xc4211d8120, 0x0, 0x0)
	/go/src/gopkg.in/rana/ora.v4/stmt.go:209 +0x27e fp=0xc42130b628 sp=0xc42130b380
gopkg.in/rana/ora%2ev4.(*Stmt).closeWithRemove(0xc4211d8120, 0x101010101010101, 0x10100000001)
	/go/src/gopkg.in/rana/ora.v4/stmt.go:130 +0x70 fp=0xc42130b658 sp=0xc42130b628
gopkg.in/rana/ora%2ev4.(*Stmt).Close(0xc4211d8120, 0x0, 0x0)
	/go/src/gopkg.in/rana/ora.v4/stmt.go:115 +0x2b fp=0xc42130b680 sp=0xc42130b658
gopkg.in/rana/ora%2ev4.(*DrvStmt).Close(0xc4208ea270, 0xf1dec8, 0xc4201c0150)
	/go/src/gopkg.in/rana/ora.v4/drvStmt.go:37 +0x7d fp=0xc42130b6b8 sp=0xc42130b680
database/sql.(*driverStmt).Close(0xc420a1cb40, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:472 +0x9c fp=0xc42130b6e0 sp=0xc42130b6b8
database/sql.(*Rows).close(0xc4205acf00, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:2443 +0x193 fp=0xc42130b720 sp=0xc42130b6e0
database/sql.(*Rows).Close(0xc4205acf00, 0xa5119e, 0x56)
	/usr/local/go/src/database/sql/sql.go:2418 +0x3d fp=0xc42130b758 sp=0xc42130b720
main.processMessage(0xc4214749c0, 0x201)
	/go/src/gomq/consumers/AcctRecordNoSqlProcessor/main.go:385 +0x74e fp=0xc42130bcb8 sp=0xc42130b758
main.memcacheCallback(0xc421211200, 0x2e7, 0x600, 0xc421211200)
	/go/src/gomq/consumers/AcctRecordNoSqlProcessor/main.go:491 +0x2aa fp=0xc42130bd78 sp=0xc42130bcb8
go-jasperlib/kestrel.(*MemcacheReader).readerRoutine(0xc4200ae2c0)
	/go/src/go-jasperlib/kestrel/reader.go:259 +0x4b8 fp=0xc42130bfd8 sp=0xc42130bd78
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42130bfe0 sp=0xc42130bfd8
created by go-jasperlib/kestrel.NewMemcacheReader
	/go/src/go-jasperlib/kestrel/reader.go:556 +0x312

```

**Comment by tgulacsi** [comment]
Can you share anything about the code?
How do you use ora?
As I see, through database/sql. But exactly how? SELECT in a loop, or?
Do you use Context, timeout?

**Comment by freedombird9** [comment]
Sure, an example would be:
```

ctx, _ := context.WithTimeout(context.Background(), 10*time.Second)
rows, err := pvgdb.QueryContext(ctx, "select scheduleid, newscheduleid from acctbillsettings          where acctid=:acctid and rownum=1", acctId)
if err != nil {
    return -1, err
}
defer rows.Close()
```

The queries are really simple, no loop involved.  And I ported them over from Java code to improve the performance.  They've been working well before 1.8 without context.  I'm indeed using the database/sql package.

**Comment by tgulacsi** [comment]
Ok, my last question: do the timeouts fire?
I suppose yes, as that's the only new functionality introduced with 1.8.
Maybe logging those timeouts? Or raise them?

What is db.MaxIdleConns / db.MaxOpenConns? Are those limits reached
somewhere? Do you run multiple queries concurrently, even accidentally?


Yongfeng Zhang <notifications@github.com> ezt írta (időpont: 2017. máj. 4.,
Cs, 23:54):

**Comment by freedombird9** [comment]
Yes, they fire pretty often. Actually they're logged by the library directly: "Context deadline exceeded".  MaxIdleConns=20, MaxOpenConns=30.  I'm not sure if they're reached or not.  But possibly, our app can scale up to 500 goroutines making the queries concurrently.

**Comment by tgulacsi** [comment]
Can you try first this:

```
diff --git a/ses.go b/ses.go
index 9d579e9..5fdea18 100644
--- a/ses.go
+++ b/ses.go
@@ -795,9 +795,9 @@ func (ses *Ses) Break() (err error) {
        if err != nil {
                return errE(err)
        }
-       ses.RLock()
+       ses.Lock()
        env := ses.Env()
-       defer ses.RUnlock()
+       defer ses.Unlock()
        if r := C.OCIBreak(unsafe.Pointer(ses.ocisvcctx), env.ocierr); r == C.OCI_ERROR {
                return errE(env.ociError())
        }
```

then 

```
diff --git a/drvStmt_go1_8.go b/drvStmt_go1_8.go
index a94877d..07edb9b 100644
--- a/drvStmt_go1_8.go
+++ b/drvStmt_go1_8.go
@@ -41,7 +41,8 @@ func (ds *DrvStmt) ExecContext(ctx context.Context, values []driver.NamedValue)
        select {
        case <-ctx.Done():
                if err = ctx.Err(); isCanceled(err) {
-                       ds.stmt.ses.Break()
+                       //ds.stmt.ses.Break()
+                       return nil, err
                }
        case err = <-done:
        }
```

?

Maybe we can't call OCIBreak parallel with other executing connections.

**Comment by freedombird9** [comment]
Applied that patch. Still got:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x7fe79c3e3193]
runtime stack:
runtime.throw(0xa4a0c2, 0x2a)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:274 +0x2db
goroutine 416700 [syscall, locked to thread]:
runtime.cgocall(0x9210b0, 0xc421a59320, 0xa4960f)
	/usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc421a592e0 sp=0xc421a592a0
gopkg.in/rana/ora%2ev4._Cfunc_OCIAttrGet(0x7fe720038300, 0x35, 0xc420ee20d8, 0xc420ee20dc, 0x5, 0x12c0940, 0xc400000000)
	gopkg.in/rana/ora.v4/_obj/_cgo_gotypes.go:347 +0x4d fp=0xc421a59320 sp=0xc421a592e0
gopkg.in/rana/ora%2ev4.(*Rset).paramAttr.func1(0x7fe720038300, 0xc400000035, 0xc420ee20d8, 0xc420ee20dc, 0x5, 0x12c0940, 0xc420ee20d8)
	/go/src/gopkg.in/rana/ora.v4/rset.go:944 +0xfc fp=0xc421a59368 sp=0xc421a59320
gopkg.in/rana/ora%2ev4.(*Rset).paramAttr(0xc420e82380, 0x7fe720038300, 0xc420ee20d8, 0x0, 0xc400000005, 0x0, 0x0)
	/go/src/gopkg.in/rana/ora.v4/rset.go:950 +0x6e fp=0xc421a593b0 sp=0xc421a59368
gopkg.in/rana/ora%2ev4.(*Rset).open(0xc420e82380, 0xc420bae5a0, 0x7fe768034e48, 0x0, 0x0)
	/go/src/gopkg.in/rana/ora.v4/rset.go:545 +0xd03 fp=0xc421a59b98 sp=0xc421a593b0
gopkg.in/rana/ora%2ev4.(*Stmt).qryC(0xc420bae5a0, 0xf21de0, 0xc420f951a0, 0xc42195ebf0, 0x1, 0x1, 0xc420e82380, 0x0, 0x0)
	/go/src/gopkg.in/rana/ora.v4/stmt.go:446 +0x3c4 fp=0xc421a59f18 sp=0xc421a59b98
gopkg.in/rana/ora%2ev4.(*DrvStmt).QueryContext.func1(0xc421a83080, 0xc4204e20e0, 0xc4204e20d8, 0xf21de0, 0xc420f951a0, 0xc42195ebf0, 0x1, 0x1)
	/go/src/gopkg.in/rana/ora.v4/drvStmt_go1_8.go:77 +0xa6 fp=0xc421a59fa0 sp=0xc421a59f18
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc421a59fa8 sp=0xc421a59fa0
created by gopkg.in/rana/ora%2ev4.(*DrvStmt).QueryContext
	/go/src/gopkg.in/rana/ora.v4/drvStmt_go1_8.go:83 +0x30c
```

It's from `_Cfunc_OCIAttrGet()`.  I've also seen it before. It seems the segfault signal can be from several C functions.

**Comment by tgulacsi** [comment]
Both patches? The second part eliminated the call to OCIBreak, which I
suspected to cause the signal.
But now I see that patch was incomplete (only commented out the Break in
ExecContext, and leaved it in QueryContext).

If you bear with me, please  eliminate ses.Break for the sake of
experiment: add a "return nil" as the first row of ses.Break in ses.go!

I see no smoking gun in paramAttr.

Yongfeng Zhang <notifications@github.com> ezt írta (időpont: 2017. máj. 5.,
P, 20:31):

**Comment by freedombird9** [comment]
No luck either.  One run got the same error as above.  Another run got:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f5d12c8de72 pc=0x7f5d12c8de6b]
runtime stack:
runtime.throw(0xa49b22, 0x2a)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:274 +0x2db
goroutine 25647 [syscall, locked to thread]:
runtime.cgocall(0x91fe50, 0xc421356cc8, 0xa4906f)
	/usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc421356c88 sp=0xc421356c48
gopkg.in/rana/ora%2ev4._Cfunc_OCIDescriptorFree(0x7f5ca40bf950, 0x7f5c00000035, 0x0)
	gopkg.in/rana/ora.v4/_obj/_cgo_gotypes.go:626 +0x4d fp=0xc421356cc8 sp=0xc421356c88
gopkg.in/rana/ora%2ev4.(*Rset).open.func2.1(0x7f5ca40bf950, 0x35, 0x0)
	/go/src/gopkg.in/rana/ora.v4/rset.go:472 +0x68 fp=0xc421356d00 sp=0xc421356cc8
gopkg.in/rana/ora%2ev4.(*Rset).open.func2(0xc420f18240, 0x3, 0x3)
	/go/src/gopkg.in/rana/ora.v4/rset.go:473 +0x5b fp=0xc421356d38 sp=0xc421356d00
runtime.call32(0x0, 0xa53210, 0xc420ea8350, 0x1800000018)
	/usr/local/go/src/runtime/asm_amd64.s:514 +0x48 fp=0xc421356d68 sp=0xc421356d38
panic(0x99e1a0, 0xf0e530)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf fp=0xc421356e00 sp=0xc421356d68
runtime.panicmem()
	/usr/local/go/src/runtime/panic.go:63 +0x5e fp=0xc421356e20 sp=0xc421356e00
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:290 +0x29f fp=0xc421356e70 sp=0xc421356e20
gopkg.in/rana/ora%2ev4.(*Stmt).Cfg(0xc420d2d560, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/gopkg.in/rana/ora.v4/stmt.go:91 +0x166 fp=0xc4213573b0 sp=0xc421356e70
gopkg.in/rana/ora%2ev4.(*Rset).open(0xc4216e40e0, 0xc420d2d560, 0x7f5cb0065f20, 0x0, 0x0)
	/go/src/gopkg.in/rana/ora.v4/rset.go:530 +0x9d2 fp=0xc421357b98 sp=0xc4213573b0
gopkg.in/rana/ora%2ev4.(*Stmt).qryC(0xc420d2d560, 0xf218e0, 0xc421510540, 0xc420d16a00, 0x1, 0x1, 0xc4216e40e0, 0x0, 0x0)
	/go/src/gopkg.in/rana/ora.v4/stmt.go:446 +0x3c4 fp=0xc421357f18 sp=0xc421357b98
gopkg.in/rana/ora%2ev4.(*DrvStmt).QueryContext.func1(0xc42136a840, 0xc421160070, 0xc421160058, 0xf218e0, 0xc421510540, 0xc420d16a00, 0x1, 0x1)
	/go/src/gopkg.in/rana/ora.v4/drvStmt_go1_8.go:77 +0xa6 fp=0xc421357fa0 sp=0xc421357f18
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc421357fa8 sp=0xc421357fa0
created by gopkg.in/rana/ora%2ev4.(*DrvStmt).QueryContext
	/go/src/gopkg.in/rana/ora.v4/drvStmt_go1_8.go:83 +0x30c
goroutine 1 [semacquire, 1 minutes]:
sync.runtime_Semacquire(0xc42020e2e8)
	/usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc42020e2dc)
	/usr/local/go/src/sync/waitgroup.go:131 +0x7a
go-jasperlib/kestrel.(*MemcacheReader).Wait(0xc42020e2c0)
	/go/src/go-jasperlib/kestrel/reader.go:685 +0x12a
main.main()
	/go/src/gomq/consumers/AcctRecordNoSqlProcessor/main.go:596 +0x659
```
The issue looks like a `database/sql` bug to me now.  https://github.com/golang/go/issues/20160

**Comment by freedombird9** [comment]
But the database/sql issue seems to be a bit different.

**Comment by freedombird9** [comment]
Yeah, I tried with the recent `database/sql` patches.  I still got the same errors.  So it doesn't seem to be like a standard library issue either.

**Comment by tgulacsi** [comment]
Can you give me a minimal reproducing case?

**Comment by tgulacsi** [comment]
Can you try the "nonblocking" branch, at least 40855ed ?
`(cd $GOPATH/src/gopkg.in/rana/ora.v4 && git fetch origin && git checkout -b nonblocking origin/nonblocking)`

**Comment by freedombird9** [comment]
It worked! Thanks for your work.

**Comment by tgulacsi** [comment]
The head-banging thing is that in retrospect, the error is understandable
and the fix is trivial.

Yongfeng Zhang <notifications@github.com> ezt írta (időpont: 2017. máj.
20., Szo 3:15):
