### ISSUE TITLE
Query which contains CLOB column(s) stops execution

### ISSUE THREAD

**Issue by mguggi** [rana/ora#237]
When I try to query data from **_gv$sqlstats_** the driver stops after some rows. Queries without CLOB columns work as expected. 

This is my the function:
```golang
func New(base mb.BaseMetricSet) (mb.MetricSet, error) {

	config := struct{}{}

	logp.Info("EXPERIMENTAL: The oracle sqlstats metricset is experimental")

	if err := base.Module().UnpackConfig(&config); err != nil {
		return nil, err
	}

	// Configure the driver to return large floats as strings
	logp.Debug(selector, "Connect to host: %s", base.HostData().URI)
	ora.SetCfg(ora.Cfg().SetNumberBigFloat(ora.S))
	db, err := sql.Open("ora", base.HostData().URI)
	if err != nil {
		return nil, errors.Wrapf(err, "%s open connection failed", selector)
	}

	stmt, err := db.Prepare(
		"select /* metricset: sqlstats */ * from gv$sqlstats")

	if err != nil {
		return nil, errors.Wrapf(err, "%s failed prepare statement", selector)
	}

	return &MetricSet{
		BaseMetricSet: base,
		db:            db,
		stmt:          stmt,
	}, nil
}

// Fetch methods implements the data gathering and data conversion to the right format
// It returns the event which is then forward to the output. In case of an error, a
// descriptive error must be returned.
func (m *MetricSet) Fetch() ([]common.MapStr, error) {

	// Make connection timeout aware
	timeout := m.BaseMetricSet.Module().Config().Timeout
	logp.Debug(selector, "Set timout to: %s", timeout)
	ctx, _ := context.WithTimeout(context.Background(), timeout)

	rows, err := m.stmt.QueryContext(ctx)
	if err != nil {
		return nil, errors.Wrapf(err, "%s failed query data", selector)
	}
	events := []common.MapStr{}
	results, _ := oracle.Scan(rows)
	for _, result := range results {
		data, _ := schema.Apply(result)
		events = append(events, data)
	}

	return events, nil
}
```

I have this problem with go 1.9.2 Oracle Instant Client 12.2.0.1.0  and ora v4 (v4.1.14).

Below is an excerpt from the stack trace:
```
goroutine 39 [select, locked to thread]:
runtime.gopark(0x302eb50, 0x0, 0x2f9cb42, 0x6, 0x18, 0x1)
        /home/mguggi/public/go-1.9.2/src/runtime/proc.go:287 +0x12c
runtime.selectgo(0xc420163f50, 0xc4202146c0)
        /home/mguggi/public/go-1.9.2/src/runtime/select.go:395 +0x1149
runtime.ensureSigM.func1()
        /home/mguggi/public/go-1.9.2/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
        /home/mguggi/public/go-1.9.2/src/runtime/asm_amd64.s:2337 +0x1

goroutine 40 [chan receive]:
github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/libbeat/service.HandleSignals.func1(0xc42006c900, 0xc42001ce04, 0xc4200db540)
        /home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/libbeat/service/service.go:32 +0x38
created by github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/libbeat/service.HandleSignals
        /home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/libbeat/service/service.go:31 +0x106

goroutine 42 [runnable, locked to thread]:
github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/rana/ora%2ev4._Cfunc_OCILobRead2(0x4df0428, 0x4df0510, 0x7f700c07a578, 0xc421978000, 0x0, 0x1, 0xc421836000, 0x100000, 0x1, 0x0, ...)
        github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/rana/ora.v4/_obj/_cgo_gotypes.go:926 +0x50
github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/rana/ora%2ev4.(*lobReader).Read.func2(0xc421836000, 0x100000, 0x100000, 0x4df0428, 0x4df0510, 0x7f700c07a578, 0xc421978000, 0x0, 0x1, 0xc421836000, ...)
        /home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/rana/ora.v4/defLob.go:304 +0x23c
github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/rana/ora%2ev4.(*lobReader).Read(0xc420222ac0, 0xc421836000, 0x100000, 0x100000, 0x0, 0x0, 0x0)
        /home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/rana/ora.v4/defLob.go:297 +0x44a
github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/rana/ora%2ev4.(*lobReader).WriteTo(0xc420222ac0, 0x418b4c0, 0xc4201044d0, 0x0, 0x0, 0x0)
        /home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/rana/ora.v4/defLob.go:341 +0x1c4
io.copyBuffer(0x418b4c0, 0xc4201044d0, 0x418bcc0, 0xc420222ac0, 0x0, 0x0, 0x0, 0x2da6160, 0x0, 0x418bcc0)
        /home/mguggi/public/go-1.9.2/src/io/io.go:382 +0x30a
io.Copy(0x418b4c0, 0xc4201044d0, 0x418bcc0, 0xc420222ac0, 0xc420222ac0, 0x0, 0x0)
        /home/mguggi/public/go-1.9.2/src/io/io.go:362 +0x68
github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/rana/ora%2ev4.(*defLob).Bytes(0xc42014c000, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/rana/ora.v4/defLob.go:90 +0x604
github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/rana/ora%2ev4.(*defLob).value(0xc42014c000, 0x4, 0x2bbaa20, 0xc4201c8010, 0x0, 0x0)
        /home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/rana/ora.v4/defLob.go:148 +0x124
github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/rana/ora%2ev4.(*DrvQueryResult).Next(0xc4202fe268, 0xc4202f6a00, 0x4b, 0x4b, 0x0, 0x0)
        /home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/rana/ora.v4/drvQueryResult.go:55 +0x1f4
database/sql.(*Rows).nextLocked(0xc4203c8000, 0xc420e30000)
        /home/mguggi/public/go-1.9.2/src/database/sql/sql.go:2463 +0xc4
database/sql.(*Rows).Next.func1()
        /home/mguggi/public/go-1.9.2/src/database/sql/sql.go:2442 +0x3c
database/sql.withLock(0x4199b40, 0xc4203c8030, 0xc420e35898)
        /home/mguggi/public/go-1.9.2/src/database/sql/sql.go:2867 +0x65
database/sql.(*Rows).Next(0xc4203c8000, 0xc420077020)
        /home/mguggi/public/go-1.9.2/src/database/sql/sql.go:2441 +0x7a
github.com/mguggi/oraclebeat/module/oracle.Scan(0xc4203c8000, 0x4219468, 0xc420208300, 0x0, 0x0, 0x0)
        /home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/module/oracle/oracle.go:70 +0x4fc
github.com/mguggi/oraclebeat/module/oracle/sqlstats.(*MetricSet).Fetch(0xc420088be0, 0x2, 0x2, 0x2, 0xc42018a0c0, 0xc420229bc8)
        /home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/module/oracle/sqlstats/sqlstats.go:87 +0x1e5
github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module.(*metricSetWrapper).multiEventFetch(0xc4200db520, 0x7f7027557be0, 0xc420088be0, 0x41a9880, 0xc4203848d0)
        /home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:238 +0x4f
github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module.(*metricSetWrapper).fetch(0xc4200db520, 0x41a9880, 0xc4203848d0)
        /home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:222 +0x112
github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module.(*metricSetWrapper).startPeriodicFetching(0xc4200db520, 0x41a9880, 0xc4203848d0)
        /home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:199 +0x5d
github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module.(*metricSetWrapper).run(0xc4200db520, 0xc4202147e0, 0xc42006ca80)
        /home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:186 +0x59a
github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module.(*Wrapper).Start.func1(0xc42001cf50, 0xc4202147e0, 0xc42006ca80, 0xc4200db520)
        /home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:110 +0xbd
created by github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module.(*Wrapper).Start
        /home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:106 +0x146

goroutine 43 [semacquire]:
sync.runtime_Semacquire(0xc42001cf5c)
        /home/mguggi/public/go-1.9.2/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc42001cf50)
        /home/mguggi/public/go-1.9.2/src/sync/waitgroup.go:131 +0x72
github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module.(*Wrapper).Start.func2(0xc42001cf50, 0xc42006ca80, 0xc42006b540)
        /home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:116 +0x2f
created by github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module.(*Wrapper).Start
        /home/mguggi/work/beats/src/github.com/mguggi/oraclebeat/vendor/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:115 +0x198

```
Any Ideas how I can solve my issue?

**Comment by tgulacsi** [comment]
It's stuck in OCILobRead2, on the C side. If you enable logging, an "OCILobRead2(...) piece=... off=... amt=... length=..." row may be usable.

**Comment by tgulacsi** [comment]
You have two errors in MetricSet.Fetch: 
1. you ignore the returned context.CancelFunc,
2. you don't close *sql.Rows returned by QueryContext.

**Comment by tgulacsi** [comment]
3. don't ignore error returned by oracle.Scan
4. where is rows.Next() called? inside oracle.Scan?

**Comment by tgulacsi** [comment]
See TestLobIssue237 in z_lob_test.go at b2b8d03!

**Comment by mguggi** [comment]
@tgulacsi Thanks for the quick response and the provided test case. 

> 1. you ignore the returned context.CancelFunc,

Oh, thank you for the hint.

> 2. you don't close *sql.Rows returned by QueryContext.

I thought it will be closed automatically. Have read the following in the documentation:

```golang
func (rs *Rows) Close() error
```
_Close closes the Rows, preventing further enumeration. If Next is called and returns false and there are no further result sets, the Rows are closed automatically and it will suffice to check the result of Err. Close is idempotent and does not affect the result of Err._

> 3. don't ignore error returned by oracle.Scan

Yes, that's a dirty programming style. I will fix it ASAP.

> 4. where is rows.Next() called? inside oracle.Scan?

Jap, this method is called in oracle.Scan. I will merge the `CLOB` stuff in this method and try it tomorrow again.

**Comment by mguggi** [comment]
@tgulacsi 
I've seen there is a new and simpler oracle driver `goracle.v2`. In my case I won't  use Oracle specific stuff and I want use only the `database/sql` API. 

Is it advisable to switch to the slim version of the `oracle` driver? And if so, can I use the same method to query the `CLOB` type?

**Comment by tgulacsi** [comment]
Yes, goracle.v2 is better, IMO.

See TestStatsWithLob test function in z_lob_test.go - TL;DR select into
&goracle.Lob{}.

mguggi <notifications@github.com> ezt írta (időpont: 2017. nov. 27., H,
22:47):

**Comment by tgulacsi** [comment]
You're right about the documentation of rows.Close - it is closed iff you exhaust the Rows with .Next - but if not (return in Scan error, for example), it'll linger there - so I think it is easier to `defer rows.Close()`.

**Comment by mguggi** [comment]
@tgulacsi  Thank you for providing the test cases in both projects. I've changed my project to the other driver and I very happy with this decision. Again big thanks for the hints to my code.
