### ISSUE TITLE
sql db.Exec fail to insert "" to blob,runtime error: index out of range

### ISSUE THREAD

**Issue by hnzouzc** [rana/ora#257]
table:
   create table blob_sample( id integer, payload blob);

func fatal(err error){
	if err !=nil{
		log.Fatal(err)
	}
}

 func testOracle(){
	db ,err := sql.Open("ora","user/pwd@//127.0.0.1:1521/orcltest")
	fatal(err)
	defer db.Close()
	err = db.Ping()
	fatal(err)
	//ora.Cfg().Stm
ids := []int64{2,3,4}
	datas := []string{"123443",""," "}
	for i:=0;i<len(ids);i++{
		err := insertBlobDataByByte(db,ids[i],[]byte(datas[i]))
		if err !=nil{
			fmt.Printf("fail to insert id:%d,data:%s,err:%v\n",ids[i],datas[i],err)
			continue
		}
		data,err:=readBlobDataByByte(db,ids[i])
		if err!=nil{
			fmt.Printf("fail to get id:%d,err:%v\n",ids[i],err)
		}else{
			fmt.Printf("id:%d,data:%s,len:%d\n",ids[i],data,len(data))
		}
	}
}

  func insertBlobDataByByte(db *sql.DB,id int64,abc []byte)error{
  	_,err := db.Exec("insert into blob_sample(id,payload)values(:1,:2)",id,abc)
  	return err
  }

do import oracle init.
ab is not empty,<nil>
id:2,data:123443,len:6
fail to insert id:3,data:,err:Stmt.exeC.func1 recovered: runtime error: index out of range
goroutine 1 [running]:
gopkg.in/rana/ora%2ev4.getStack(0x0, 0x0)
        /mnt/e/gosrc/jpush-src-go-64/src/gopkg.in/rana/ora.v4/util.go:188 +0x92
gopkg.in/rana/ora%2ev4.errR(0xc421205490, 0x1, 0x1, 0xc4212054d0, 0x456aee)
        /mnt/e/gosrc/jpush-src-go-64/src/gopkg.in/rana/ora.v4/util.go:198 +0xe5

**Comment by hnzouzc** [comment]
@tgulacsi  thanks, it work well
