### ISSUE TITLE
SIGTRAP trace after CTRL-C

### ISSUE THREAD

**Issue by schmooser** [rana/ora#65]
Hi,

I have a SIGTRAP trace every time I close the program which uses rana/ora driver. 

How to fix this? What am I doing wrong?

Environment: Oracle XE 11.2 running on CentOS 6.5, OS X El Capitan, Oracle Instant client 11.2, go 1.5.3

Example source code - https://gist.github.com/schmooser/6fa4535475d922652d60

Output:
```
$ go run *.go
2016/02/27 12:28:05 [debug] ses closed
2016/02/27 12:28:05 [debug] srv closed
2016/02/27 12:28:05 [debug] env closed
2016/02/27 12:28:05 Result: 2016.02.27 12:28:16  <-- I press Ctrl-C here
^CSIGTRAP: trace trap
PC=0x405733d m=0

goroutine 0 [idle]:
runtime.morestack()
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:302 +0x1d

goroutine 5 [syscall]:
runtime.notetsleepg(0x432cdd8, 0x6fc22d851, 0x0)
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/lock_sema.go:264 +0x86 fp=0xc820029f38 sp=0xc820029ef8
runtime.timerproc()
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/time.go:209 +0xde fp=0xc820029fc0 sp=0xc820029f38
runtime.goexit()
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc820029fc8 sp=0xc820029fc0
created by runtime.addtimerLocked
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/time.go:116 +0x11f

goroutine 1 [sleep]:
time.Sleep(0x6fc23ac00)
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/time.go:59 +0xf9
main.main()
        /Users/rbd/Projects/go/src/github.com/schmooser/go-oracle/rana-ora/main.go:95 +0x229

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1

rax    0xc820009a38
rbx    0x432d4a0
rcx    0x432d160
rdx    0x0
rdi    0x2
rsi    0x432d160
rbp    0xc820009a50
rsp    0xc820009a40
r8     0xc820009ee8
r9     0x8a2b60c
r10    0x44cb9fa573a
r11    0x202
r12    0x11e4f14ec0fb4
r13    0x11e4edfa6d630
r14    0x1436c268d4973200
r15    0x8
rip    0x405733d
rflags 0x246
cs     0x2b
fs     0x0
gs     0x0
exit status 2

```

**Comment by tgulacsi** [comment]
As I see even the env is closed, so nothing is connecting this with ora.

Is this reproducible even with "go build -o /tmp/x && /tmp/x" ?

**Comment by schmooser** [comment]
Unfortunately it didn't help. I even upgraded to go 1.6, same thing.

It's definitely the driver causes this because when I mock execution there is no such trace on Ctrl-C (though return code is the same - 2).

**Comment by tgulacsi** [comment]
I can't reproduce it on linux/amd64.
See "issue65" branch,

    cd examples/sigtrap && go run ./sigtrap.go

**Comment by schmooser** [comment]
I executed the example you provided, new error occurred:

```
[~/Projects/repos/go-rana-ora/examples/sigtrap] issue65* ± ./sigtrap
2016/03/02 10:04:55 [debug] ses closed
2016/03/02 10:04:55 [debug] srv closed
2016/03/02 10:04:55 [debug] env closed
2016/03/02 10:04:55 Result: 2016.03.02 10:05:08
2016/03/02 10:04:56 INT self
runtime: newstack sp=0xc820009a48 stack=[0xc820088000, 0xc82008bfb0]
        morebuf={pc:0x7fff848c8eaa sp:0xc820009a50 lr:0x0}
        sched={pc:0x403eba9 sp:0xc820009a48 lr:0x0 ctxt:0x0}
fatal error: runtime: stack split at bad time

runtime stack:
runtime.throw(0x4273240, 0x20)
        /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x90
runtime.newstack()
        /usr/local/Cellar/go/1.6/libexec/src/runtime/stack.go:834 +0x582
runtime.morestack()
        /usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:359 +0x7f

goroutine 1 [syscall]:

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 +0x1

```

Can it be connected with OS X Oracle drivers / Go?

**Comment by schmooser** [comment]
Although it's still an issue on OS X I doublechecked the example on Linux in Docker container and there is no SIGTRAP trace.

Let's close the issue.
