### ISSUE TITLE
Nil pointer dereference error

### ISSUE THREAD

**Issue by omerkirk** [rana/ora#68]
I started to see panics like below after starting to use go 1.6. I am not really sure if this is related to some garbage collected pointer that should have been kept. It maybe related to some missing bindings from C code. Please let me know if this doesn't look like a driver issue and I will close it. 

The following is the way I create the statement, nothing new but here it is: 

```
    stmt, err := rr.DB.PrepareNamed(sqlMatchHeaderCount)
	if err != nil {
		return 0, err
	}
	defer stmt.Close()
	var count int
	err = stmt.Get(&count, map[string]interface{}{"headerID": headerID, "appID": appID})
```

I am using a library called jmoiron/sqlx, but it is only a wrapper around database/sql for easy scanning of values into structs. It is not responsible for creating or cleaning pointers to statements.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x530caa]

goroutine 1402 [running]:
panic(0x9360e0, 0xc8200100e0)
        /usr/local/go1.6/src/runtime/panic.go:464 +0x3e6
gopkg.in/rana/ora%2ev3.(*DrvStmt).sysName(0xc83d3fc6a8, 0x0, 0x0)
        /home/kokteyl/go/src/gopkg.in/rana/ora.v3/drvStmt.go:101 +0xaa
gopkg.in/rana/ora%2ev3.(*DrvStmt).log(0xc83d3fc6a8, 0x40ec01, 0x0, 0x0, 0x0)
        /home/kokteyl/go/src/gopkg.in/rana/ora.v3/drvStmt.go:108 +0x50
gopkg.in/rana/ora%2ev3.(*DrvStmt).Close(0xc83d3fc6a8, 0x0, 0x0)
        /home/kokteyl/go/src/gopkg.in/rana/ora.v3/drvStmt.go:33 +0x49
database/sql.(*driverConn).finalClose(0xc83d1fc460, 0x0, 0x0)
        /usr/local/go1.6/src/database/sql/sql.go:356 +0xc4
database/sql.(finalCloser).(database/sql.finalClose)-fm(0x0, 0x0)
        /usr/local/go1.6/src/database/sql/sql.go:449 +0x40
database/sql.(*driverConn).Close(0xc83d1fc460, 0x0, 0x0)
        /usr/local/go1.6/src/database/sql/sql.go:349 +0x24b
database/sql.(*DB).putConn(0xc8200c0420, 0xc83d1fc460, 0x0, 0x0)
        /usr/local/go1.6/src/database/sql/sql.go:909 +0x27d
database/sql.(*driverConn).releaseConn(0xc83d1fc460, 0x0, 0x0)
        /usr/local/go1.6/src/database/sql/sql.go:284 +0x3d
database/sql.(*driverConn).(database/sql.releaseConn)-fm(0x0, 0x0)
        /usr/local/go1.6/src/database/sql/sql.go:1078 +0x34

```

**Comment by tgulacsi** [comment]
It won't panic, but I don't know why drvStmt.stmt/ses/... anything there is nil.
