### ISSUE TITLE
go pointer to go pointer

### ISSUE THREAD

**Issue by fils** [rana/ora#87]
With go version go1.6.2 darwin/amd64  and ora 3.4 I am starting to see an error about 

**Go pointer to Go pointer**

Was wondering if this was a known thing and if there was something I need to be doing.  Mac os X 10.11.4.   

```
 Ses.Prep.func1 recovered: runtime error: cgo argument has Go pointer to Go pointer
goroutine 5 [running]:
gopkg.in/rana/ora%2ev3.errR(0xc8200fc980, 0x1, 0x1, 0x0, 0x0)
	/Users/dfils/src/go/src/gopkg.in/rana/ora.v3/util.go:231 +0x97
gopkg.in/rana/ora%2ev3.(*Ses).Prep.func1(0xc8200fce28)
	/Users/dfils/src/go/src/gopkg.in/rana/ora.v3/ses.go:245 +0xa2
panic(0x45fea00, 0xc82019e520)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
gopkg.in/rana/ora%2ev3._cgoCheckPointer0(0x45099a0, 0xc8201a60e8, 0x0, 0x0, 0x0, 0xa048ee0)
	??:0 +0x4d
gopkg.in/rana/ora%2ev3.(*Stmt).attr(0xc8201a6000, 0xc8201a60e8, 0x1800000004, 0x0, 0x0)
	/Users/dfils/src/go/src/gopkg.in/rana/ora.v3/stmt.go:1152 +0xc4
gopkg.in/rana/ora%2ev3.(*Ses).Prep(0xc8201a2000, 0xc82016f200, 0x5d1, 0x0, 0x0, 0x0, 0xc8201a6000, 0x0, 0x0)
	/Users/dfils/src/go/src/gopkg.in/rana/ora.v3/ses.go:291 +0x904
gopkg.in/rana/ora%2ev3.(*Con).Prepare(0xc820196080, 0xc82016f200, 0x5d1, 0x0, 0x0, 0x0, 0x0)
	/Users/dfils/src/go/src/gopkg.in/rana/ora.v3/conn.go:117 +0xff
database/sql.(*DB).queryConn(0xc8200badc0, 0xc8201a20e0, 0xc82019e3e0, 0xc82016f200, 0x5d1, 0x0, 0x0, 0x0, 0xc82016f200, 0x0, ...)
	/usr/local/go/src/database/sql/sql.go:1110 +0x31a
database/sql.(*DB).query(0xc8200badc0, 0xc82016f200, 0x5d1, 0x0, 0x0, 0x0, 0x501, 0x5d1, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:1078 +0x126
database/sql.(*DB).Query(0xc8200badc0, 0xc82016f200, 0x5d1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:1061 +0xa3
opencoredata.org/ocdServices/janus.RockEval(0xc820139500, 0xc82013f040)
	/Users/dfils/src/go/src/opencoredata.org/ocdServices/janus/rockeval.go:77 +0x8f7
github.com/emicklei/go-restful.(*Container).dispatch.func5(0xc820139500, 0xc82013f040)
	/Users/dfils/src/go/src/github.com/emicklei/go-restful/container.go:192 +0x31
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc820139590, 0xc820139500, 0xc82013f040)
	/Users/dfils/src/go/src/github.com/emicklei/go-restful/filter.go:21 +0x9f
github.com/emicklei/go-restful.Container.OPTIONSFilter(0x49bb3b8, 0x0, 0x0, 0xc8200e0a20, 0x0, 0xc820028098, 0x1, 0x1, 0x0, 0x47dba38, ...)
	/Users/dfils/src/go/src/github.com/emicklei/go-restful/options_filter.go:14 +0x180
github.com/emicklei/go-restful.(Container).OPTIONSFilter-fm(0xc820139500, 0xc82013f040, 0xc820139590)
	/Users/dfils/src/go/src/opencoredata.org/ocdServices/main.go:61 +0x59
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc820139590, 0xc820139500, 0xc82013f040)
	/Users/dfils/src/go/src/github.com/emicklei/go-restful/filter.go:19 +0x81
github.com/emicklei/go-restful.CrossOriginResourceSharing.Filter(0xc82000b960, 0x1, 0x1, 0xc82000b970, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dfils/src/go/src/github.com/emicklei/go-restful/cors_filter.go:37 +0x1bc
github.com/emicklei/go-restful.(CrossOriginResourceSharing).Filter-fm(0xc820139500, 0xc82013f040, 0xc820139590)
	/Users/dfils/src/go/src/opencoredata.org/ocdServices/main.go:58 +0x64
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc820139590, 0xc820139500, 0xc82013f040)
	/Users/dfils/src/go/src/github.com/emicklei/go-restful/filter.go:19 +0x81
github.com/emicklei/go-restful.(*Container).dispatch(0xc82005caf0, 0x8ba5a78, 0xc8200f2750, 0xc82016c2a0)
	/Users/dfils/src/go/src/github.com/emicklei/go-restful/container.go:194 +0xe44
github.com/emicklei/go-restful.(*Container).(github.com/emicklei/go-restful.dispatch)-fm(0x8ba5a78, 0xc8200f2750, 0xc82016c2a0)
	/Users/dfils/src/go/src/github.com/emicklei/go-restful/container.go:76 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc82012b3d0, 0x8ba5a78, 0xc8200f2750, 0xc82016c2a0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc8200e0a20, 0x8ba5a78, 0xc8200f2750, 0xc82016c2a0)
	/usr/local/go/src/net/http/server.go:1910 +0x17d
github.com/emicklei/go-restful.Container.ServeHTTP(0xc82010f1c0, 0x8, 0x8, 0xc8200e0a20, 0x0, 0xc82000b980, 0x2, 0x2, 0x0, 0x47dba38, ...)
	/Users/dfils/src/go/src/github.com/emicklei/go-restful/container.go:212 +0x48
github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc82005caf0, 0x8ba5a78, 0xc8200f2750, 0xc82016c2a0)
	<autogenerated>:23 +0xcb
net/http.serverHandler.ServeHTTP :<nil>
2016/05/18 10:45:19 <nil>
```

**Comment by fils** [comment]
I should have included my gcc info

```
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
```

**Comment by tgulacsi** [comment]
Strange. https://github.com/rana/ora/blob/v3.4/stmt.go#L1152 says
stmt.mu.Unlock, which is not cgo related. What commit do you have?


Douglas Fils <notifications@github.com> ezt írta (időpont: 2016. máj. 18.,
Sze, 17:54):

**Comment by fils** [comment]
@tgulacsi  you guys did some fixes for me before and I think I pulled a specific commit.   Wonder if that is messing something up.   Perhaps I have an older specific commit somewhere.     

I did a ```go get gopkg.in/rana/ora.v3``` fresh, but perhaps I have some refernce laying around in my paths?    Is there a good way to clean them out and make sure I am running the latest version?

**Comment by fils** [comment]
@tgulacsi I may have found the issue.   

```
Fils:src root# cd gopkg.in/rana/ora.v3/
Fils:ora.v3 root# git status
On branch issue36
Your branch is up-to-date with 'origin/issue36'.
nothing to commit, working directory clean
```

I need to get off this branch I suspect and get current.    I also have src/go/src/github.com/rana/ora which might be good to have.  Though one is likely first and being seen.   I thought go get would have overridden these.   so I need to get the master branch and pull?  what do you think....

**Comment by tgulacsi** [comment]
master branch or the specific v3.4 tag both sufficient.
cd $GOPATH/src/gopkg.in/rana/ora.v3
git checkout -f master
git pull

Douglas Fils <notifications@github.com> ezt írta (időpont: 2016. máj. 18.,
Sze, 21:26):

**Comment by fils** [comment]
```Fils:ocdServices dfils$ export CGO_CFLAGS=-I/Users/dfils/src/oracle/instantclient_11_2/sdk/include
Fils:ocdServices dfils$ export CGO_LDFLAGS="-L/Users/dfils/src/oracle/instantclient_11_2 -lclntsh"
Fils:ocdServices dfils$ export DYLD_LIBRARY_PATH=/Users/dfils/src/oracle/instantclient_11_2:$DYLD_LIBRARY_PATH
Fils:ocdServices dfils$ go run main.go
# pkg-config --cflags oci8
Package oci8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `oci8.pc'
to the PKG_CONFIG_PATH environment variable
No package 'oci8' found
pkg-config: exit status 1
```

I wonder if my client SDK is too old now?

**Comment by tgulacsi** [comment]
Nope - look at the readme, and copy a good looking *.pc from contrib/ to
your PKG_CONFIG_PATH as oci8.pc.
We have transferred from env vars to pkg-config some months ago.

Douglas Fils <notifications@github.com> ezt írta (időpont: 2016. máj. 18.,
Sze, 22:48):

**Comment by fils** [comment]
@tgulacsi sorry for the delay. Was traveling back and then off-line over the weekend.   I need to keep closer tabs on developments.  :)   Thanks for the help, setting up the oci8 file worked just fine.
